// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEd9_KUWEXsL1MfUDBEyEOXptm3gH38E',
    appId: '1:157638292284:web:37956fbd61c573b02ea439',
    messagingSenderId: '157638292284',
    projectId: 'mynews-a34bc',
    authDomain: 'mynews-a34bc.firebaseapp.com',
    storageBucket: 'mynews-a34bc.appspot.com',
    measurementId: 'G-9BJFS7VWNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbj7XFoZGBCtVtjeNo8duqHr6R_JFagj8',
    appId: '1:157638292284:android:e1ee1cd8eae567c22ea439',
    messagingSenderId: '157638292284',
    projectId: 'mynews-a34bc',
    storageBucket: 'mynews-a34bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKm8NkGRMXIFL7QLRR5y5m0IGKdse-kqc',
    appId: '1:157638292284:ios:fc082d6613f7ea022ea439',
    messagingSenderId: '157638292284',
    projectId: 'mynews-a34bc',
    storageBucket: 'mynews-a34bc.appspot.com',
    iosBundleId: 'com.example.myNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKm8NkGRMXIFL7QLRR5y5m0IGKdse-kqc',
    appId: '1:157638292284:ios:fc082d6613f7ea022ea439',
    messagingSenderId: '157638292284',
    projectId: 'mynews-a34bc',
    storageBucket: 'mynews-a34bc.appspot.com',
    iosBundleId: 'com.example.myNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEd9_KUWEXsL1MfUDBEyEOXptm3gH38E',
    appId: '1:157638292284:web:3e3a92cc23defc882ea439',
    messagingSenderId: '157638292284',
    projectId: 'mynews-a34bc',
    authDomain: 'mynews-a34bc.firebaseapp.com',
    storageBucket: 'mynews-a34bc.appspot.com',
    measurementId: 'G-ZK2G2406YZ',
  );
}
